### ISSUE TITLE
not downloading over 50 folders

### ISSUE THREAD

**Issue by IkariDevGIT** [fumiichan/asuka#43] opened 2021-12-04 23:31 UTC
my command: asuka search --page 2 -q parody:"kono subarashii sekai ni syukufuku o" -o C:\Users\einea\Downloads\llww\m\asuka-1.0.0-win-x64\download

my folder: 50 folders inside

it is not downloading anymore, but when I change the output folder then it works

**Comment by aikoofujimotoo** [comment] 2021-12-07 07:10
Will look into it

**Comment by aikoofujimotoo** [comment] 2021-12-07 07:17
Can you provide any screenshot? Can't really reproduce on my end.

**Comment by aikoofujimotoo** [comment] 2021-12-07 07:38
This bug was fixed on 1.1 Release Candidate 1 due to issue where `--page` option isn't working.

**Comment by fumiichan** [comment] 2022-07-08 18:41
Fixed in 1.1.0.0 release.

**Closed by fumiichan** 2022-07-08 18:41 UTC
Labels: bug, on-progress
